sudo: false
language: android

android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.0
        - android-23
        - extra-android-m2repository
        - extra-google-google_play_services

script:
    ./gradlew build

notifications:
    email: false
