sudo: false
language: android

android:
    components:
        - platform-tools
        - tools
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
        - extra-google-google_play_services
        - extra-google-m2repository
        - addon-google_apis-google-19

script:
    ./gradlew build

notifications:
    email: false
